runtime: python27
api_version: 1 
threadsafe: false
libraries:
- name: jinja2
  version: latest
  
handlers: 
# - url: /cgi   
#   script: cgimain.py

# - url: /wsgi
#   script: wsgiapp.wsgimain

- url: /.*
  script: main.app